sudo: false

language: node_js

node_js: '6'

cache:
  directories:
    - "node_modules"

env:
  - PRODUCTION=1

install:
  - npm install
  - npm install coveralls

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
